project 'MVVM Example.xcodeproj/'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM Example

  target 'MVVM ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM ExampleUITests' do
    # Pods for testing
  end
  
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod "RxGesture"
  pod 'SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher'
  pod 'ImageSlideshow'
  pod 'ImageSlideshow/Kingfisher'
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'RealmSwift'

end
